// lib/formOptions.ts
// This file is the single source of truth for all dropdown and checkbox options in the profile form.

// --- Education Related ---
export const COUNTRY_OPTIONS = [
    { value: "", label: "Please Select" },
    { value: "Switzerland", label: "Switzerland" },
    { value: "Germany", label: "Germany" },
    { value: "Italy", label: "Italy" },
    { value: "France", label: "France" },
    { value: "Afghanistan", label: "Afghanistan" },
    { value: "Albania", label: "Albania" },
    { value: "Algeria", label: "Algeria" },
    { value: "Andorra", label: "Andorra" },
    { value: "Angola", label: "Angola" },
    { value: "Antigua and Barbuda", label: "Antigua and Barbuda" },
    { value: "Argentina", label: "Argentina" },
    { value: "Armenia", label: "Armenia" },
    { value: "Australia", label: "Australia" },
    { value: "Austria", label: "Austria" },
    { value: "Azerbaijan", label: "Azerbaijan" },
    { value: "Bahamas", label: "Bahamas" },
    { value: "Bahrain", label: "Bahrain" },
    { value: "Bangladesh", label: "Bangladesh" },
    { value: "Barbados", label: "Barbados" },
    { value: "Belarus", label: "Belarus" },
    { value: "Belgium", label: "Belgium" },
    { value: "Belize", label: "Belize" },
    { value: "Benin", label: "Benin" },
    { value: "Bhutan", label: "Bhutan" },
    { value: "Bolivia", label: "Bolivia" },
    { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
    { value: "Botswana", label: "Botswana" },
    { value: "Brazil", label: "Brazil" },
    { value: "Brunei", label: "Brunei" },
    { value: "Bulgaria", label: "Bulgaria" },
    { value: "Burkina Faso", label: "Burkina Faso" },
    { value: "Burundi", label: "Burundi" },
    { value: "Cabo Verde", label: "Cabo Verde" },
    { value: "Cambodia", label: "Cambodia" },
    { value: "Cameroon", label: "Cameroon" },
    { value: "Canada", label: "Canada" },
    { value: "Central African Republic", label: "Central African Republic" },
    { value: "Chad", label: "Chad" },
    { value: "Chile", label: "Chile" },
    { value: "China", label: "China" },
    { value: "Colombia", label: "Colombia" },
    { value: "Comoros", label: "Comoros" },
    { value: "Congo, Democratic Republic of the", label: "Congo, Democratic Republic of the" },
    { value: "Congo, Republic of the", label: "Congo, Republic of the" },
    { value: "Costa Rica", label: "Costa Rica" },
    { value: "Cote d'Ivoire", label: "Cote d'Ivoire" }, // Note: ' converted to '
    { value: "Croatia", label: "Croatia" },
    { value: "Cuba", label: "Cuba" },
    { value: "Cyprus", label: "Cyprus" },
    { value: "Czech Republic", label: "Czech Republic" },
    { value: "Denmark", label: "Denmark" },
    { value: "Djibouti", label: "Djibouti" },
    { value: "Dominica", label: "Dominica" },
    { value: "Dominican Republic", label: "Dominican Republic" },
    { value: "Ecuador", label: "Ecuador" },
    { value: "Egypt", label: "Egypt" },
    { value: "El Salvador", label: "El Salvador" },
    { value: "Equatorial Guinea", label: "Equatorial Guinea" },
    { value: "Eritrea", label: "Eritrea" },
    { value: "Estonia", label: "Estonia" },
    { value: "Eswatini", label: "Eswatini" },
    { value: "Ethiopia", label: "Ethiopia" },
    { value: "Fiji", label: "Fiji" },
    { value: "Finland", label: "Finland" },
    { value: "Gabon", label: "Gabon" },
    { value: "Gambia", label: "Gambia" },
    { value: "Georgia", label: "Georgia" },
    { value: "Ghana", label: "Ghana" },
    { value: "Greece", label: "Greece" },
    { value: "Grenada", label: "Grenada" },
    { value: "Guatemala", label: "Guatemala" },
    { value: "Guinea", label: "Guinea" },
    { value: "Guinea-Bissau", label: "Guinea-Bissau" },
    { value: "Guyana", label: "Guyana" },
    { value: "Haiti", label: "Haiti" },
    { value: "Holy See (Vatican City)", label: "Holy See (Vatican City)" },
    { value: "Honduras", label: "Honduras" },
    { value: "Hungary", label: "Hungary" },
    { value: "Iceland", label: "Iceland" },
    { value: "India", label: "India" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Iran", label: "Iran" },
    { value: "Iraq", label: "Iraq" },
    { value: "Ireland", label: "Ireland" },
    { value: "Israel", label: "Israel" },
    { value: "Jamaica", label: "Jamaica" },
    { value: "Japan", label: "Japan" },
    { value: "Jordan", label: "Jordan" },
    { value: "Kazakhstan", label: "Kazakhstan" },
    { value: "Kenya", label: "Kenya" },
    { value: "Kiribati", label: "Kiribati" },
    { value: "Kosovo", label: "Kosovo" },
    { value: "Kuwait", label: "Kuwait" },
    { value: "Kyrgyzstan", label: "Kyrgyzstan" },
    { value: "Laos", label: "Laos" },
    { value: "Latvia", label: "Latvia" },
    { value: "Lebanon", label: "Lebanon" },
    { value: "Lesotho", label: "Lesotho" },
    { value: "Liberia", label: "Liberia" },
    { value: "Libya", label: "Libya" },
    { value: "Liechtenstein", label: "Liechtenstein" },
    { value: "Lithuania", label: "Lithuania" },
    { value: "Luxembourg", label: "Luxembourg" },
    { value: "Madagascar", label: "Madagascar" },
    { value: "Malawi", label: "Malawi" },
    { value: "Malaysia", label: "Malaysia" },
    { value: "Maldives", label: "Maldives" },
    { value: "Mali", label: "Mali" },
    { value: "Malta", label: "Malta" },
    { value: "Marshall Islands", label: "Marshall Islands" },
    { value: "Mauritania", label: "Mauritania" },
    { value: "Mauritius", label: "Mauritius" },
    { value: "Mexico", label: "Mexico" },
    { value: "Micronesia", label: "Micronesia" },
    { value: "Moldova", label: "Moldova" },
    { value: "Monaco", label: "Monaco" },
    { value: "Mongolia", label: "Mongolia" },
    { value: "Montenegro", label: "Montenegro" },
    { value: "Morocco", label: "Morocco" },
    { value: "Mozambique", label: "Mozambique" },
    { value: "Myanmar (Burma)", label: "Myanmar (Burma)" },
    { value: "Namibia", label: "Namibia" },
    { value: "Nauru", label: "Nauru" },
    { value: "Nepal", label: "Nepal" },
    { value: "Netherlands", label: "Netherlands" },
    { value: "New Zealand", label: "New Zealand" },
    { value: "Nicaragua", label: "Nicaragua" },
    { value: "Niger", label: "Niger" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "North Korea", label: "North Korea" },
    { value: "North Macedonia", label: "North Macedonia" },
    { value: "Norway", label: "Norway" },
    { value: "Oman", label: "Oman" },
    { value: "Pakistan", label: "Pakistan" },
    { value: "Palau", label: "Palau" },
    { value: "Palestine, State of", label: "Palestine, State of" },
    { value: "Panama", label: "Panama" },
    { value: "Papua New Guinea", label: "Papua New Guinea" },
    { value: "Paraguay", label: "Paraguay" },
    { value: "Peru", label: "Peru" },
    { value: "Philippines", label: "Philippines" },
    { value: "Poland", label: "Poland" },
    { value: "Portugal", label: "Portugal" },
    { value: "Qatar", label: "Qatar" },
    { value: "Romania", label: "Romania" },
    { value: "Russia", label: "Russia" },
    { value: "Rwanda", label: "Rwanda" },
    { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
    { value: "Saint Lucia", label: "Saint Lucia" },
    { value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines" },
    { value: "Samoa", label: "Samoa" },
    { value: "San Marino", label: "San Marino" },
    { value: "Sao Tome and Principe", label: "Sao Tome and Principe" },
    { value: "Saudi Arabia", label: "Saudi Arabia" },
    { value: "Senegal", label: "Senegal" },
    { value: "Serbia", label: "Serbia" },
    { value: "Seychelles", label: "Seychelles" },
    { value: "Sierra Leone", label: "Sierra Leone" },
    { value: "Singapore", label: "Singapore" },
    { value: "Slovakia", label: "Slovakia" },
    { value: "Slovenia", label: "Slovenia" },
    { value: "Solomon Islands", label: "Solomon Islands" },
    { value: "Somalia", label: "Somalia" },
    { value: "South Africa", label: "South Africa" },
    { value: "South Korea", label: "South Korea" },
    { value: "South Sudan", label: "South Sudan" },
    { value: "Spain", label: "Spain" },
    { value: "Sri Lanka", label: "Sri Lanka" },
    { value: "Sudan", label: "Sudan" },
    { value: "Suriname", label: "Suriname" },
    { value: "Sweden", label: "Sweden" },
    { value: "Syria", label: "Syria" },
    { value: "Taiwan", label: "Taiwan" },
    { value: "Tajikistan", label: "Tajikistan" },
    { value: "Tanzania", label: "Tanzania" },
    { value: "Thailand", label: "Thailand" },
    { value: "Timor-Leste", label: "Timor-Leste" },
    { value: "Togo", label: "Togo" },
    { value: "Tonga", label: "Tonga" },
    { value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
    { value: "Tunisia", label: "Tunisia" },
    { value: "Turkey", label: "Turkey" },
    { value: "Turkmenistan", label: "Turkmenistan" },
    { value: "Tuvalu", label: "Tuvalu" },
    { value: "Uganda", label: "Uganda" },
    { value: "Ukraine", label: "Ukraine" },
    { value: "United Arab Emirates", label: "United Arab Emirates" },
    { value: "UK", label: "UK" },
    { value: "USA", label: "USA" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "Uzbekistan", label: "Uzbekistan" },
    { value: "Vanuatu", label: "Vanuatu" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Yemen", label: "Yemen" },
    { value: "Zambia", label: "Zambia" },
    { value: "Zimbabwe", label: "Zimbabwe" }
];

export const GENERAL_FIELD_OPTIONS = [
  { value: "", label: "Please Select" },
  { value: "Arts and Design", label: "Arts and Design" },
  { value: "Business and Economics", label: "Business and Economics" },
  { value: "Education", label: "Education" },
  { value: "Engineering", label: "Engineering" },
  { value: "Environmental Studies and Agriculture", label: "Environmental Studies and Agriculture" },
  { value: "Humanities", label: "Humanities" },
  { value: "Law and Legal Studies", label: "Law and Legal Studies" },
  { value: "Mathematics", label: "Mathematics" },
  { value: "Medical and Health Sciences", label: "Medical and Health Sciences" },
  { value: "Music", label: "Music" },
  { value: "Science", label: "Science (Natural/Life)" },
  { value: "Social Sciences", label: "Social Sciences" },
  { value: "Technology / IT", label: "Technology / IT" },
  { value: "Other", label: "Other (Not Listed)" }
];

export const SPECIFIC_FIELD_OPTIONS = [
  { value: "", label: "Please Select" },
  { value: "Accounting", label: "Accounting" },
  { value: "Actuarial Science", label: "Actuarial Science" },
  { value: "Aerospace Engineering", label: "Aerospace Engineering" },
  { value: "Agricultural Sciences", label: "Agricultural Sciences" },
  { value: "Anthropology / Ethnology", label: "Anthropology / Ethnology" },
  { value: "Applied Mathematics", label: "Applied Mathematics" },
  { value: "Archaeology", label: "Archaeology" },
  { value: "Architecture", label: "Architecture" },
  { value: "Art History", label: "Art History" },
  { value: "Banking & Finance", label: "Banking & Finance" },
  { value: "Biochemistry", label: "Biochemistry" },
  { value: "Bioinformatics", label: "Bioinformatics" },
  { value: "Biology / Life Sciences", label: "Biology / Life Sciences" },
  { value: "Biomedical Engineering", label: "Biomedical Engineering" },
  { value: "Biomedical Sciences / Biomedicine", label: "Biomedical Sciences / Biomedicine" },
  { value: "Biotechnology", label: "Biotechnology" },
  { value: "Business Administration / Management", label: "Business Administration / Management" },
  { value: "Business Informatics / Information Systems", label: "Business Informatics / Information Systems" },
  { value: "Chemical Engineering", label: "Chemical Engineering" },
  { value: "Chemistry", label: "Chemistry" },
  { value: "Civil Engineering", label: "Civil Engineering" },
  { value: "Classics (Ancient Greek/Latin)", label: "Classics (Ancient Greek/Latin)" },
  { value: "Communication / Media Studies", label: "Communication / Media Studies" },
  { value: "Computational Biology", label: "Computational Biology" },
  { value: "Computational Science / Engineering", label: "Computational Science / Engineering" },
  { value: "Computer Science / Informatics", label: "Computer Science / Informatics" },
  { value: "Data Science", label: "Data Science" },
  { value: "Dentistry", label: "Dentistry" },
  { value: "Design (Graphic, Industrial, etc.)", label: "Design (Graphic, Industrial, etc.)" },
  { value: "Earth Sciences / Geosciences", label: "Earth Sciences / Geosciences" },
  { value: "Economics", label: "Economics" },
  { value: "Educational Sciences", label: "Educational Sciences" },
  { value: "Electrical Engineering", label: "Electrical Engineering" },
  { value: "Energy Science / Engineering", label: "Energy Science / Engineering" },
  { value: "English Language and Literature", label: "English Language and Literature" },
  { value: "Environmental Engineering", label: "Environmental Engineering" },
  { value: "Environmental Sciences", label: "Environmental Sciences" },
  { value: "Film Studies", label: "Film Studies" },
  { value: "Finance", label: "Finance" },
  { value: "Food Science", label: "Food Science" },
  { value: "French Language and Literature", label: "French Language and Literature" },
  { value: "Geography", label: "Geography" },
  { value: "Geomatics / Geomatic Engineering", label: "Geomatics / Geomatic Engineering" },
  { value: "German Language and Literature", label: "German Language and Literature" },
  { value: "Health Sciences", label: "Health Sciences" },
  { value: "History", label: "History" },
  { value: "Human Resources Management", label: "Human Resources Management" },
  { value: "Industrial Engineering", label: "Industrial Engineering" },
  { value: "Information Technology", label: "Information Technology" },
  { value: "International Affairs / Relations", label: "International Affairs / Relations" },
  { value: "Italian Language and Literature", label: "Italian Language and Literature" },
  { value: "Journalism", label: "Journalism" },
  { value: "Landscape Architecture", label: "Landscape Architecture" },
  { value: "Law", label: "Law" },
  { value: "Linguistics", label: "Linguistics" },
  { value: "Logistics / Supply Chain Management", label: "Logistics / Supply Chain Management" },
  { value: "Management, Technology & Economics", label: "Management, Technology & Economics" },
  { value: "Marketing", label: "Marketing" },
  { value: "Materials Science / Engineering", label: "Materials Science / Engineering" },
  { value: "Mathematics", label: "Mathematics" },
  { value: "Mechanical Engineering", label: "Mechanical Engineering" },
  { value: "Mechatronics", label: "Mechatronics" },
  { value: "Media Engineering", label: "Media Engineering" },
  { value: "Medicine (Human)", label: "Medicine (Human)" },
  { value: "Microbiology", label: "Microbiology" },
  { value: "Microengineering", label: "Microengineering" },
  { value: "Movement Sciences / Sports Science", label: "Movement Sciences / Sports Science" },
  { value: "Musicology / Music", label: "Musicology / Music" },
  { value: "Nanotechnology / Nanoscience", label: "Nanotechnology / Nanoscience" },
  { value: "Neuroscience", label: "Neuroscience" },
  { value: "Nuclear Engineering", label: "Nuclear Engineering" },
  { value: "Nursing", label: "Nursing" },
  { value: "Nutritional Science", label: "Nutritional Science" },
  { value: "Pharmaceutical Sciences / Pharmacy", label: "Pharmaceutical Sciences / Pharmacy" },
  { value: "Philosophy", label: "Philosophy" },
  { value: "Physics", label: "Physics" },
  { value: "Political Science", label: "Political Science" },
  { value: "Psychology", label: "Psychology" },
  { value: "Public Health", label: "Public Health" },
  { value: "Quantitative Finance", label: "Quantitative Finance" },
  { value: "Religious Studies / Theology", label: "Religious Studies / Theology" },
  { value: "Robotics, Systems and Control", label: "Robotics, Systems and Control" },
  { value: "Social Work", label: "Social Work" },
  { value: "Sociology", label: "Sociology" },
  { value: "Software Engineering / Systems", label: "Software Engineering / Systems" },
  { value: "Spanish Language and Literature", label: "Spanish Language and Literature" },
  { value: "Spatial Development / Planning", label: "Spatial Development / Planning" },
  { value: "Statistics", label: "Statistics" },
  { value: "Sustainable Development", label: "Sustainable Development" },
  { value: "Theatre / Performing Arts", label: "Theatre / Performing Arts" },
  { value: "Tourism / Hospitality Management", label: "Tourism / Hospitality Management" },
  { value: "Translation Studies", label: "Translation Studies" },
  { value: "Veterinary Medicine", label: "Veterinary Medicine" },
  { value: "Other", label: "Other (Not Listed)" }
];

export const DEGREE_TYPE_OPTIONS = [
  { value: "", label: "Please Select" },
  // High School / Secondary Education
  { value: "High School Diploma", label: "High School Diploma" },
  { value: "A-Levels", label: "A-Levels (UK)" },
  { value: "International Baccalaureate", label: "International Baccalaureate (IB)" },
  { value: "Matura", label: "Matura / Maturità" },
  { value: "Abitur", label: "Abitur (Germany)" },
  { value: "Baccalauréat", label: "Baccalauréat (France)" },
  { value: "European Baccalaureate", label: "European Baccalaureate" },
  // Associate Degrees
  { value: "AA", label: "AA (Associate of Arts)" },
  { value: "AS", label: "AS (Associate of Science)" },
  { value: "AAS", label: "AAS (Associate of Applied Science)" },
  // Bachelor's Degrees
  { value: "BSc", label: "BSc (Bachelor of Science)" },
  { value: "BA", label: "BA (Bachelor of Arts)" },
  // Master's Degrees
  { value: "MSc", label: "MSc (Master of Science)" },
  { value: "MA", label: "MA (Master of Arts)" },
  { value: "MAS", label: "MAS (Master Advanced Studies)" },
  { value: "MBA", label: "MBA (Master of Business Administration)" },
  // Doctoral
  { value: "PhD", label: "PhD (Doctorate)" },
  // Swiss-Specific Certifications
  { value: "CAS", label: "CAS (Certificate Advanced Studies)" },
  { value: "DAS", label: "DAS (Diploma Advanced Studies)" },
  { value: "Federal Diploma", label: "Federal Diploma (Eidg. Diplom)" }
];

export const GRADE_OPTIONS = [
  { value: "", label: "Select if applicable" },
  { value: "4-4.5", label: "4.0 - 4.5" },
  { value: "4.5-5", label: "4.5 - 5.0" },
  { value: "5-5.5", label: "5.0 - 5.5" },
  { value: "5.5-6", label: "5.5 - 6.0" },
];

// --- Experience Related ---
export const POSITION_TYPE_OPTIONS = [
  { value: "", label: "Please Select" },
  { value: "Full-time", label: "Full-time" },
  { value: "Part-time", label: "Part-time" },
  { value: "Internship", label: "Internship" },
  { value: "Working Student", label: "Working Student" },
];

// --- Skills Related ---
export const LANGUAGE_PROFICIENCY_OPTIONS = [
  { value: "", label: "Choose Level" },
  { value: "None", label: "None" },
  { value: "Beginner", label: "Beginner (A1-A2)" },
  { value: "Intermediate", label: "Intermediate (B1-B2)" },
  { value: "Advanced", label: "Advanced (C1)" },
  { value: "Fluent", label: "Fluent/Native (C2)" },
];

export const SKILL_PROFICIENCY_OPTIONS = [
    { value: "", label: "Select proficiency" },
    { value: "Beginner", label: "Beginner - Basic knowledge, need guidance" },
    { value: "Intermediate", label: "Intermediate - Working knowledge, occasional assistance" },
    { value: "Advanced", label: "Advanced - Comprehensive knowledge, work independently" },
    { value: "Expert", label: "Expert - Deep knowledge, can teach others" },
    { value: "Professional", label: "Professional - Mastery level, recognized authority" },
];

export const INDUSTRY_SKILL_OPTIONS = [
    { value: "Banking & Financial Services", label: "Banking & Financial Services" },
    { value: "Consulting", label: "Consulting" },
    { value: "Technology & IT", label: "Technology & IT" },
    { value: "Pharmaceuticals, Life Sciences & Biotechnology", label: "Pharmaceuticals, Life Sciences & Biotechnology" },
    { value: "Engineering & Manufacturing", label: "Engineering & Manufacturing" },
    { value: "Research & Development", label: "Research & Development" },
    { value: "Public Sector, Administration & NGOs", label: "Public Sector, Administration & NGOs" },
    { value: "Consumer Goods & Retail", label: "Consumer Goods & Retail" }
];

// --- Preferences Related ---
export const DURATION_OPTIONS = [
    { value: "", label: "Please Select" },
    { value: "0-3 months", label: "0-3 months" },
    { value: "3-6 months", label: "3-6 months" },
    { value: "6-12 months", label: "6-12 months" },
    { value: "12+ months", label: "12+ months" },
];

export const NOTICE_PERIOD_OPTIONS = [
    { value: "", label: "Please Select" },
    { value: "1", label: "1 month" },
    { value: "2", label: "2 months" },
    { value: "3", label: "3 months" },
    { value: "4", label: "4 months" },
    { value: "5", label: "5 months" },
    { value: "6", label: "6 months" },
    { value: "7+", label: "7+ months" },
];

// --- Phone Country Codes ---
// Complete list of international calling codes organized for optimal UX
// Popular countries first (Swiss/European context), then alphabetically
export const PHONE_COUNTRY_CODE_OPTIONS = [
  // === Popular / Common (for Swiss context) ===
  { code: "+41", flag: "🇨🇭", label: "Switzerland" },
  { code: "+49", flag: "🇩🇪", label: "Germany" },
  { code: "+33", flag: "🇫🇷", label: "France" },
  { code: "+39", flag: "🇮🇹", label: "Italy" },
  { code: "+43", flag: "🇦🇹", label: "Austria" },
  { code: "+44", flag: "🇬🇧", label: "United Kingdom" },
  { code: "+1", flag: "🇺🇸", label: "United States" },
  { code: "+1", flag: "🇨🇦", label: "Canada" },

  // === All Countries (Alphabetical) ===
  { code: "+93", flag: "🇦🇫", label: "Afghanistan" },
  { code: "+355", flag: "🇦🇱", label: "Albania" },
  { code: "+213", flag: "🇩🇿", label: "Algeria" },
  { code: "+1-684", flag: "🇦🇸", label: "American Samoa" },
  { code: "+376", flag: "🇦🇩", label: "Andorra" },
  { code: "+244", flag: "🇦🇴", label: "Angola" },
  { code: "+1-264", flag: "🇦🇮", label: "Anguilla" },
  { code: "+672", flag: "🇦🇶", label: "Antarctica" },
  { code: "+1-268", flag: "🇦🇬", label: "Antigua and Barbuda" },
  { code: "+54", flag: "🇦🇷", label: "Argentina" },
  { code: "+374", flag: "🇦🇲", label: "Armenia" },
  { code: "+297", flag: "🇦🇼", label: "Aruba" },
  { code: "+61", flag: "🇦🇺", label: "Australia" },
  { code: "+994", flag: "🇦🇿", label: "Azerbaijan" },
  { code: "+1-242", flag: "🇧🇸", label: "Bahamas" },
  { code: "+973", flag: "🇧🇭", label: "Bahrain" },
  { code: "+880", flag: "🇧🇩", label: "Bangladesh" },
  { code: "+1-246", flag: "🇧🇧", label: "Barbados" },
  { code: "+375", flag: "🇧🇾", label: "Belarus" },
  { code: "+32", flag: "🇧🇪", label: "Belgium" },
  { code: "+501", flag: "🇧🇿", label: "Belize" },
  { code: "+229", flag: "🇧🇯", label: "Benin" },
  { code: "+1-441", flag: "🇧🇲", label: "Bermuda" },
  { code: "+975", flag: "🇧🇹", label: "Bhutan" },
  { code: "+591", flag: "🇧🇴", label: "Bolivia" },
  { code: "+387", flag: "🇧🇦", label: "Bosnia and Herzegovina" },
  { code: "+267", flag: "🇧🇼", label: "Botswana" },
  { code: "+55", flag: "🇧🇷", label: "Brazil" },
  { code: "+246", flag: "🇮🇴", label: "British Indian Ocean Territory" },
  { code: "+1-284", flag: "🇻🇬", label: "British Virgin Islands" },
  { code: "+673", flag: "🇧🇳", label: "Brunei" },
  { code: "+359", flag: "🇧🇬", label: "Bulgaria" },
  { code: "+226", flag: "🇧🇫", label: "Burkina Faso" },
  { code: "+257", flag: "🇧🇮", label: "Burundi" },
  { code: "+855", flag: "🇰🇭", label: "Cambodia" },
  { code: "+237", flag: "🇨🇲", label: "Cameroon" },
  { code: "+238", flag: "🇨🇻", label: "Cape Verde" },
  { code: "+1-345", flag: "🇰🇾", label: "Cayman Islands" },
  { code: "+236", flag: "🇨🇫", label: "Central African Republic" },
  { code: "+235", flag: "🇹🇩", label: "Chad" },
  { code: "+56", flag: "🇨🇱", label: "Chile" },
  { code: "+86", flag: "🇨🇳", label: "China" },
  { code: "+61", flag: "🇨🇽", label: "Christmas Island" },
  { code: "+61", flag: "🇨🇨", label: "Cocos Islands" },
  { code: "+57", flag: "🇨🇴", label: "Colombia" },
  { code: "+269", flag: "🇰🇲", label: "Comoros" },
  { code: "+682", flag: "🇨🇰", label: "Cook Islands" },
  { code: "+506", flag: "🇨🇷", label: "Costa Rica" },
  { code: "+385", flag: "🇭🇷", label: "Croatia" },
  { code: "+53", flag: "🇨🇺", label: "Cuba" },
  { code: "+599", flag: "🇨🇼", label: "Curaçao" },
  { code: "+357", flag: "🇨🇾", label: "Cyprus" },
  { code: "+420", flag: "🇨🇿", label: "Czech Republic" },
  { code: "+243", flag: "🇨🇩", label: "Democratic Republic of the Congo" },
  { code: "+45", flag: "🇩🇰", label: "Denmark" },
  { code: "+253", flag: "🇩🇯", label: "Djibouti" },
  { code: "+1-767", flag: "🇩🇲", label: "Dominica" },
  { code: "+1-809", flag: "🇩🇴", label: "Dominican Republic" },
  { code: "+670", flag: "🇹🇱", label: "East Timor" },
  { code: "+593", flag: "🇪🇨", label: "Ecuador" },
  { code: "+20", flag: "🇪🇬", label: "Egypt" },
  { code: "+503", flag: "🇸🇻", label: "El Salvador" },
  { code: "+240", flag: "🇬🇶", label: "Equatorial Guinea" },
  { code: "+291", flag: "🇪🇷", label: "Eritrea" },
  { code: "+372", flag: "🇪🇪", label: "Estonia" },
  { code: "+251", flag: "🇪🇹", label: "Ethiopia" },
  { code: "+500", flag: "🇫🇰", label: "Falkland Islands" },
  { code: "+298", flag: "🇫🇴", label: "Faroe Islands" },
  { code: "+679", flag: "🇫🇯", label: "Fiji" },
  { code: "+358", flag: "🇫🇮", label: "Finland" },
  { code: "+594", flag: "🇬🇫", label: "French Guiana" },
  { code: "+689", flag: "🇵🇫", label: "French Polynesia" },
  { code: "+241", flag: "🇬🇦", label: "Gabon" },
  { code: "+220", flag: "🇬🇲", label: "Gambia" },
  { code: "+995", flag: "🇬🇪", label: "Georgia" },
  { code: "+233", flag: "🇬🇭", label: "Ghana" },
  { code: "+350", flag: "🇬🇮", label: "Gibraltar" },
  { code: "+30", flag: "🇬🇷", label: "Greece" },
  { code: "+299", flag: "🇬🇱", label: "Greenland" },
  { code: "+1-473", flag: "🇬🇩", label: "Grenada" },
  { code: "+590", flag: "🇬🇵", label: "Guadeloupe" },
  { code: "+1-671", flag: "🇬🇺", label: "Guam" },
  { code: "+502", flag: "🇬🇹", label: "Guatemala" },
  { code: "+44-1481", flag: "🇬🇬", label: "Guernsey" },
  { code: "+224", flag: "🇬🇳", label: "Guinea" },
  { code: "+245", flag: "🇬🇼", label: "Guinea-Bissau" },
  { code: "+592", flag: "🇬🇾", label: "Guyana" },
  { code: "+509", flag: "🇭🇹", label: "Haiti" },
  { code: "+504", flag: "🇭🇳", label: "Honduras" },
  { code: "+852", flag: "🇭🇰", label: "Hong Kong" },
  { code: "+36", flag: "🇭🇺", label: "Hungary" },
  { code: "+354", flag: "🇮🇸", label: "Iceland" },
  { code: "+91", flag: "🇮🇳", label: "India" },
  { code: "+62", flag: "🇮🇩", label: "Indonesia" },
  { code: "+98", flag: "🇮🇷", label: "Iran" },
  { code: "+964", flag: "🇮🇶", label: "Iraq" },
  { code: "+353", flag: "🇮🇪", label: "Ireland" },
  { code: "+44-1624", flag: "🇮🇲", label: "Isle of Man" },
  { code: "+972", flag: "🇮🇱", label: "Israel" },
  { code: "+1-876", flag: "🇯🇲", label: "Jamaica" },
  { code: "+81", flag: "🇯🇵", label: "Japan" },
  { code: "+44-1534", flag: "🇯🇪", label: "Jersey" },
  { code: "+962", flag: "🇯🇴", label: "Jordan" },
  { code: "+7", flag: "🇰🇿", label: "Kazakhstan" },
  { code: "+254", flag: "🇰🇪", label: "Kenya" },
  { code: "+686", flag: "🇰🇮", label: "Kiribati" },
  { code: "+383", flag: "🇽🇰", label: "Kosovo" },
  { code: "+965", flag: "🇰🇼", label: "Kuwait" },
  { code: "+996", flag: "🇰🇬", label: "Kyrgyzstan" },
  { code: "+856", flag: "🇱🇦", label: "Laos" },
  { code: "+371", flag: "🇱🇻", label: "Latvia" },
  { code: "+961", flag: "🇱🇧", label: "Lebanon" },
  { code: "+266", flag: "🇱🇸", label: "Lesotho" },
  { code: "+231", flag: "🇱🇷", label: "Liberia" },
  { code: "+218", flag: "🇱🇾", label: "Libya" },
  { code: "+423", flag: "🇱🇮", label: "Liechtenstein" },
  { code: "+370", flag: "🇱🇹", label: "Lithuania" },
  { code: "+352", flag: "🇱🇺", label: "Luxembourg" },
  { code: "+853", flag: "🇲🇴", label: "Macau" },
  { code: "+389", flag: "🇲🇰", label: "Macedonia" },
  { code: "+261", flag: "🇲🇬", label: "Madagascar" },
  { code: "+265", flag: "🇲🇼", label: "Malawi" },
  { code: "+60", flag: "🇲🇾", label: "Malaysia" },
  { code: "+960", flag: "🇲🇻", label: "Maldives" },
  { code: "+223", flag: "🇲🇱", label: "Mali" },
  { code: "+356", flag: "🇲🇹", label: "Malta" },
  { code: "+692", flag: "🇲🇭", label: "Marshall Islands" },
  { code: "+596", flag: "🇲🇶", label: "Martinique" },
  { code: "+222", flag: "🇲🇷", label: "Mauritania" },
  { code: "+230", flag: "🇲🇺", label: "Mauritius" },
  { code: "+262", flag: "🇾🇹", label: "Mayotte" },
  { code: "+52", flag: "🇲🇽", label: "Mexico" },
  { code: "+691", flag: "🇫🇲", label: "Micronesia" },
  { code: "+373", flag: "🇲🇩", label: "Moldova" },
  { code: "+377", flag: "🇲🇨", label: "Monaco" },
  { code: "+976", flag: "🇲🇳", label: "Mongolia" },
  { code: "+382", flag: "🇲🇪", label: "Montenegro" },
  { code: "+1-664", flag: "🇲🇸", label: "Montserrat" },
  { code: "+212", flag: "🇲🇦", label: "Morocco" },
  { code: "+258", flag: "🇲🇿", label: "Mozambique" },
  { code: "+95", flag: "🇲🇲", label: "Myanmar" },
  { code: "+264", flag: "🇳🇦", label: "Namibia" },
  { code: "+674", flag: "🇳🇷", label: "Nauru" },
  { code: "+977", flag: "🇳🇵", label: "Nepal" },
  { code: "+31", flag: "🇳🇱", label: "Netherlands" },
  { code: "+687", flag: "🇳🇨", label: "New Caledonia" },
  { code: "+64", flag: "🇳🇿", label: "New Zealand" },
  { code: "+505", flag: "🇳🇮", label: "Nicaragua" },
  { code: "+227", flag: "🇳🇪", label: "Niger" },
  { code: "+234", flag: "🇳🇬", label: "Nigeria" },
  { code: "+683", flag: "🇳🇺", label: "Niue" },
  { code: "+672", flag: "🇳🇫", label: "Norfolk Island" },
  { code: "+850", flag: "🇰🇵", label: "North Korea" },
  { code: "+1-670", flag: "🇲🇵", label: "Northern Mariana Islands" },
  { code: "+47", flag: "🇳🇴", label: "Norway" },
  { code: "+968", flag: "🇴🇲", label: "Oman" },
  { code: "+92", flag: "🇵🇰", label: "Pakistan" },
  { code: "+680", flag: "🇵🇼", label: "Palau" },
  { code: "+970", flag: "🇵🇸", label: "Palestine" },
  { code: "+507", flag: "🇵🇦", label: "Panama" },
  { code: "+675", flag: "🇵🇬", label: "Papua New Guinea" },
  { code: "+595", flag: "🇵🇾", label: "Paraguay" },
  { code: "+51", flag: "🇵🇪", label: "Peru" },
  { code: "+63", flag: "🇵🇭", label: "Philippines" },
  { code: "+48", flag: "🇵🇱", label: "Poland" },
  { code: "+351", flag: "🇵🇹", label: "Portugal" },
  { code: "+1-787", flag: "🇵🇷", label: "Puerto Rico" },
  { code: "+974", flag: "🇶🇦", label: "Qatar" },
  { code: "+242", flag: "🇨🇬", label: "Republic of the Congo" },
  { code: "+262", flag: "🇷🇪", label: "Reunion" },
  { code: "+40", flag: "🇷🇴", label: "Romania" },
  { code: "+7", flag: "🇷🇺", label: "Russia" },
  { code: "+250", flag: "🇷🇼", label: "Rwanda" },
  { code: "+590", flag: "🇧🇱", label: "Saint Barthelemy" },
  { code: "+290", flag: "🇸🇭", label: "Saint Helena" },
  { code: "+1-869", flag: "🇰🇳", label: "Saint Kitts and Nevis" },
  { code: "+1-758", flag: "🇱🇨", label: "Saint Lucia" },
  { code: "+590", flag: "🇲🇫", label: "Saint Martin" },
  { code: "+508", flag: "🇵🇲", label: "Saint Pierre and Miquelon" },
  { code: "+1-784", flag: "🇻🇨", label: "Saint Vincent and the Grenadines" },
  { code: "+685", flag: "🇼🇸", label: "Samoa" },
  { code: "+378", flag: "🇸🇲", label: "San Marino" },
  { code: "+239", flag: "🇸🇹", label: "Sao Tome and Principe" },
  { code: "+966", flag: "🇸🇦", label: "Saudi Arabia" },
  { code: "+221", flag: "🇸🇳", label: "Senegal" },
  { code: "+381", flag: "🇷🇸", label: "Serbia" },
  { code: "+248", flag: "🇸🇨", label: "Seychelles" },
  { code: "+232", flag: "🇸🇱", label: "Sierra Leone" },
  { code: "+65", flag: "🇸🇬", label: "Singapore" },
  { code: "+1-721", flag: "🇸🇽", label: "Sint Maarten" },
  { code: "+421", flag: "🇸🇰", label: "Slovakia" },
  { code: "+386", flag: "🇸🇮", label: "Slovenia" },
  { code: "+677", flag: "🇸🇧", label: "Solomon Islands" },
  { code: "+252", flag: "🇸🇴", label: "Somalia" },
  { code: "+27", flag: "🇿🇦", label: "South Africa" },
  { code: "+82", flag: "🇰🇷", label: "South Korea" },
  { code: "+211", flag: "🇸🇸", label: "South Sudan" },
  { code: "+34", flag: "🇪🇸", label: "Spain" },
  { code: "+94", flag: "🇱🇰", label: "Sri Lanka" },
  { code: "+249", flag: "🇸🇩", label: "Sudan" },
  { code: "+597", flag: "🇸🇷", label: "Suriname" },
  { code: "+47", flag: "🇸🇯", label: "Svalbard and Jan Mayen" },
  { code: "+268", flag: "🇸🇿", label: "Swaziland" },
  { code: "+46", flag: "🇸🇪", label: "Sweden" },
  { code: "+963", flag: "🇸🇾", label: "Syria" },
  { code: "+886", flag: "🇹🇼", label: "Taiwan" },
  { code: "+992", flag: "🇹🇯", label: "Tajikistan" },
  { code: "+255", flag: "🇹🇿", label: "Tanzania" },
  { code: "+66", flag: "🇹🇭", label: "Thailand" },
  { code: "+228", flag: "🇹🇬", label: "Togo" },
  { code: "+690", flag: "🇹🇰", label: "Tokelau" },
  { code: "+676", flag: "🇹🇴", label: "Tonga" },
  { code: "+1-868", flag: "🇹🇹", label: "Trinidad and Tobago" },
  { code: "+216", flag: "🇹🇳", label: "Tunisia" },
  { code: "+90", flag: "🇹🇷", label: "Turkey" },
  { code: "+993", flag: "🇹🇲", label: "Turkmenistan" },
  { code: "+1-649", flag: "🇹🇨", label: "Turks and Caicos Islands" },
  { code: "+688", flag: "🇹🇻", label: "Tuvalu" },
  { code: "+1-340", flag: "🇻🇮", label: "U.S. Virgin Islands" },
  { code: "+256", flag: "🇺🇬", label: "Uganda" },
  { code: "+380", flag: "🇺🇦", label: "Ukraine" },
  { code: "+971", flag: "🇦🇪", label: "United Arab Emirates" },
  { code: "+598", flag: "🇺🇾", label: "Uruguay" },
  { code: "+998", flag: "🇺🇿", label: "Uzbekistan" },
  { code: "+678", flag: "🇻🇺", label: "Vanuatu" },
  { code: "+379", flag: "🇻🇦", label: "Vatican" },
  { code: "+58", flag: "🇻🇪", label: "Venezuela" },
  { code: "+84", flag: "🇻🇳", label: "Vietnam" },
  { code: "+681", flag: "🇼🇫", label: "Wallis and Futuna" },
  { code: "+212", flag: "🇪🇭", label: "Western Sahara" },
  { code: "+967", flag: "🇾🇪", label: "Yemen" },
  { code: "+260", flag: "🇿🇲", label: "Zambia" },
  { code: "+263", flag: "🇿🇼", label: "Zimbabwe" },
];

export const JOB_TYPE_OPTIONS = ['Internship', 'Part-time', 'Career Starter (full-time)'];

// Oil & Gas hub locations in Switzerland
export const LOCATION_OPTIONS = [
    { value: "ZG",   label: "Zug" },
    { value: "ZH",   label: "Zurich" },
    { value: "GE",   label: "Geneva" },
    { value: "BE",   label: "Bern" },
    { value: "TI",   label: "Ticino" },
    { value: "GLOBAL", label: "Global" },
];

export const INDUSTRY_PREFERENCE_OPTIONS = [
    { value: "Finance",          label: "Finance" },
    { value: "Marketing",        label: "Marketing" },
    { value: "Consulting",       label: "Management Consulting" },
    { value: "HR",               label: "Human Resources (HR)" },
    { value: "Sales",            label: "Sales & Business Development" },
    { value: "MechEng",          label: "Mechanical Engineering" },
    { value: "CivilEng",         label: "Civil Engineering" },
    { value: "ElecEng",          label: "Electrical Engineering" },
    { value: "SoftEng",          label: "Software Engineering" },
    { value: "AeroEng",          label: "Aerospace Engineering" },
    { value: "SoftDev",          label: "Software Development" },
    { value: "Cyber",            label: "Cybersecurity" },
    { value: "DataAI",           label: "Data Science & AI" },
    { value: "UXUI",             label: "UX/UI Design" },
    { value: "Cloud",            label: "Cloud Computing" },
    { value: "Clinical",         label: "Clinical Internships" },
    { value: "PublicHealth",     label: "Public Health" },
    { value: "BioPharma",        label: "Biotechnology/Pharmaceuticals" },
    { value: "MedTech",          label: "Medical Technology" },
    { value: "GraphicDesign",    label: "Graphic Design" },
    { value: "FilmVideo",        label: "Film & Video Production" },
    { value: "Journalism",       label: "Journalism & Writing" },
    { value: "PR",               label: "Public Relations (PR)" },
    { value: "Advertising",      label: "Advertising" },
    { value: "EnvSci",           label: "Environmental Science" },
    { value: "Sustainability",   label: "Sustainability Consulting" },
    { value: "AgriForest",       label: "Agriculture & Forestry" },
    { value: "Renewable",        label: "Renewable Energy" },
    { value: "Legal",            label: "Legal Internships" },
    { value: "GovPolicy",        label: "Government & Public Policy" },
    { value: "Nonprofit",        label: "Nonprofit & Advocacy" },
    { value: "Teaching",         label: "Teaching" },
    { value: "SocialWork",       label: "Social Work" },
    { value: "Counseling",       label: "Counseling & Therapy" },
    { value: "EarlyEdu",         label: "Early Childhood Education" },
    { value: "HotelMgmt",        label: "Hotel Management" },
    { value: "EventPlan",        label: "Event Planning & Coordination" },
    { value: "Tourism",          label: "Tourism Marketing" },
    { value: "Ecommerce",        label: "E-commerce Operations" },
    { value: "RetailMarket",     label: "Retail Marketing" },
    { value: "CustomerService",  label: "Customer Service" },
    { value: "BrandPartner",     label: "Brand Partnerships & Licensing" }
];