-- ============================================================================
-- Migration: Add short_summary column to user_profiles
-- ============================================================================
-- Purpose: Store AI-generated 2-sentence summary for candidate cards
-- When: After CV parsing completes (alongside profile_bio)
-- Generated by: GPT-4o-mini in the parser service
-- ============================================================================

ALTER TABLE user_profiles
ADD COLUMN IF NOT EXISTS short_summary TEXT;

COMMENT ON COLUMN user_profiles.short_summary IS
  'AI-generated 2-sentence summary for card display. Generated by parser after CV extraction.';

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
